In [1]:
import pandas  as pd

In [2]:
df1=pd.read_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\Palo Alto Networks.csv')
df1

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,3,1,17,3,3,5,2,0,3
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,3,1,1,9,5,3,7,7,1,7
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,4,2,1,6,0,3,6,2,0,3
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,3,4,0,17,3,2,9,6,0,8
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,3,1,0,6,3,4,4,3,1,2

In [4]:
df=df1.copy()
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5

In [4]:
df['OverTime']

0       Yes
1        No
2       Yes
3       Yes
4        No
       ...
1465     No
1466     No
1467    Yes
1468     No
1469     No
Name: OverTime, Length: 1470, dtype: object

In [5]:
flagged_emp=df[df['OverTime']=='Yes']
flagged_emp.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
6,59,0,Travel_Rarely,1324,Research & Development,3,3,Medical,3,Female,...,4,1,3,12,3,2,1,0,0,0
11,29,0,Travel_Rarely,153,Research & Development,15,2,Life Sciences,4,Female,...,3,4,0,10,3,3,9,5,0,8

In [6]:
risky_emp = ((df['OverTime'] == 'Yes') & (df['WorkLifeBalance'] <= 2))
risky_emp.value_counts()

False    1344
True      126
Name: count, dtype: int64

In [7]:
df=pd.concat([df,risky_emp],axis=1)

In [8]:
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,0
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,1,0,8,0,1,6,4,0,5,True

In [9]:
df.rename(columns={0:'risky_emp'},inplace=True)
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risky_emp
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,1,0,8,0,1,6,4,0,5,True
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,1,10,3,3,10,7,1,7,False
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,2,0,7,3,3,0,0,0,0,False
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,0,8,3,3,8,7,3,0,False
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,4,1,6,3,3,2,2,2,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,1,17,3,3,5,2,0,3,False
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,1,1,9,5,3,7,7,1,7,False
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,2,1,6,0,3,6,2,0,3,False
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,4,0,17,3,2,9,6,0,8,False
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,1,0,6,3,4,4,3,1,2,False

In [10]:
bins=[1,2,3,4]
labels=['low','medium','high']
flagged_emp['risk_rate']=pd.cut(flagged_emp['WorkLifeBalance'],bins=bins,labels=labels,right=True,include_lowest=True)
flagged_emp['risk_rate']

0          low
2       medium
3       medium
6          low
11      medium
         ...
1450    medium
1456      high
1459    medium
1461    medium
1467    medium
Name: risk_rate, Length: 416, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']

In [11]:
df['WorkLifeBalance'].unique()

array([1, 3, 2, 4])

In [12]:
flagged_emp.reset_index(inplace=True)

In [13]:
flagged_emp.head()

,index,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risk_rate
0,0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,...,1,0,8,0,1,6,4,0,5,low
1,2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,...,2,0,7,3,3,0,0,0,0,medium
2,3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,...,3,0,8,3,3,8,7,3,0,medium
3,6,59,0,Travel_Rarely,1324,Research & Development,3,3,Medical,3,...,1,3,12,3,2,1,0,0,0,low
4,11,29,0,Travel_Rarely,153,Research & Development,15,2,Life Sciences,4,...,4,0,10,3,3,9,5,0,8,medium

In [14]:
df=pd.concat([df,flagged_emp],axis=1)
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risk_rate
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,1.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,low
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,2.0,0.0,7.0,3.0,3.0,0.0,0.0,0.0,0.0,medium
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3.0,0.0,8.0,3.0,3.0,8.0,7.0,3.0,0.0,medium
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,1.0,3.0,12.0,3.0,2.0,1.0,0.0,0.0,0.0,low
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,4.0,0.0,10.0,3.0,3.0,9.0,5.0,0.0,8.0,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risk_rate
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,1.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,low

In [16]:
flagged_emp.head(1)

,index,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risk_rate
0,0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,...,1,0,8,0,1,6,4,0,5,low

In [17]:
risky_emp.head(1)

0    True
dtype: bool

In [20]:
bins=[1,2,3,4]
labels=['low','medium','high']
df['risk_rate']=pd.cut(df['WorkLifeBalance'],bins=bins,labels=labels,right=True,include_lowest=True)
df['risk_rate']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12204\2221522973.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['risk_rate']=pd.cut(df['WorkLifeBalance'],bins=bins,labels=labels,right=True,include_lowest=True)

0          low
1       medium
2       medium
3       medium
4       medium
         ...
1465    medium
1466    medium
1467    medium
1468       low
1469      high
Name: risk_rate, Length: 1470, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']

In [ ]:
df

In [19]:
# converting worklife balance into series-
df = df.loc[:, ~df.columns.duplicated()]
df['WorkLifeBalance']
type(df['WorkLifeBalance'])

pandas.core.series.Series

In [ ]:
#df=pd.concat([df,risky_emp],axis=1)
df.rename(columns={0:'risky_emp'},inplace=True)
df

In [ ]:
del df['index']

In [ ]:
df

In [ ]:
df.to_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\unified risk rate.csv')
#risk rate column tells degreed of risk of each emp but risky emp tells us which 
#emp are at highest risk like having overtime and work life balance<=2

**engagement index**

In [11]:
cols = [
    'JobInvolvement',
    'JobSatisfaction',
    'EnvironmentSatisfaction',
    'RelationshipSatisfaction'
]

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[cols] = scaler.fit_transform(df[cols])

In [13]:
df['EngagementIndex'] = df[cols].mean(axis=1)

In [14]:
df['EngagementIndex'].describe()

count    1470.000000
mean        0.574376
std         0.168009
min         0.083333
25%         0.500000
50%         0.583333
75%         0.666667
max         1.000000
Name: EngagementIndex, dtype: float64

In [15]:
def engagement_level(score):
    if score < 0.4:
        return 'Low'
    elif score < 0.7:
        return 'Medium'
    else:
        return 'High'

df['EngagementLevel'] = df['EngagementIndex'].apply(engagement_level)

In [16]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EngagementIndex,EngagementLevel
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,0.333333,Female,...,0,8,0,1,6,4,0,5,0.500000,Medium
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,0.666667,Male,...,1,10,3,3,10,7,1,7,0.583333,Medium
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1.000000,Male,...,0,7,3,3,0,0,0,0,0.583333,Medium
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1.000000,Female,...,0,8,3,3,8,7,3,0,0.750000,High
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,0.000000,Male,...,1,6,3,3,2,2,2,2,0.500000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,0.666667,Male,...,1,17,3,3,5,2,0,3,0.833333,High
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,1.000000,Male,...,1,9,5,3,7,7,1,7,0.333333,Low
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,0.333333,Male,...,1,6,0,3,6,2,0,3,0.500000,Medium
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,1.000000,Male,...,0,17,3,2,9,6,0,8,0.666667,Medium
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,0.333333,Male,...,0,6,3,4,4,3,1,2,0.500000,Medium

engagement level tells that 'High score →
“I like my work, my team, my environment, and I’m engaged”
Low score →
“I’m mentally checked out, even if I haven’t quit yet”'

In [27]:
df.to_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\unified engagement level and risky emp .csv')

In [28]:
df.groupby('risk_rate')['EngagementIndex'].mean()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12204\3839750025.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('risk_rate')['EngagementIndex'].mean()

risk_rate
low       0.576061
medium    0.572788
high      0.578976
Name: EngagementIndex, dtype: float64

**Workload & Stress Analysis**

In [10]:
df=pd.read_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\unified engagement level and risky emp .csv')
df.head()
df2=df.copy()
df2

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risky_emp,risk_rate,EngagementIndex,EngagementLevel
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,0.333333,Female,...,0,1,6,4,0,5,True,low,0.500000,Medium
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,0.666667,Male,...,3,3,10,7,1,7,False,medium,0.583333,Medium
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1.000000,Male,...,3,3,0,0,0,0,False,medium,0.583333,Medium
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1.000000,Female,...,3,3,8,7,3,0,False,medium,0.750000,High
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,0.000000,Male,...,3,3,2,2,2,2,False,medium,0.500000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,0.666667,Male,...,3,3,5,2,0,3,False,medium,0.833333,High
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,1.000000,Male,...,5,3,7,7,1,7,False,medium,0.333333,Low
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,0.333333,Male,...,0,3,6,2,0,3,False,medium,0.500000,Medium
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,1.000000,Male,...,3,2,9,6,0,8,False,low,0.666667,Medium
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,0.333333,Male,...,3,4,4,3,1,2,False,high,0.500000,Medium

In [12]:
engagement_overtime=df2.groupby(['OverTime'])['EngagementIndex'].mean().sort_values()
engagement_overtime

OverTime
No     0.566335
Yes    0.594752
Name: EngagementIndex, dtype: float64

In [15]:
engagement_travel=df2.groupby(['BusinessTravel'])['EngagementIndex'].mean().sort_values()
engagement_travel

BusinessTravel
Travel_Rarely        0.571508
Non-Travel           0.578333
Travel_Frequently    0.583032
Name: EngagementIndex, dtype: float64

In [53]:
df2.groupby(['DistanceFromHome'])['EngagementIndex'].mean().sort_values().head()

DistanceFromHome
29    0.496914
13    0.530702
26    0.543333
25    0.543333
15    0.548077
Name: EngagementIndex, dtype: float64

In [23]:
bins=[0,5,15,30]
labels=['near','far','very far']
df2['commute']=pd.cut(df2['DistanceFromHome'],bins=bins,labels=labels,right=True,include_lowest=True)
engagement_commute=df2.groupby(['commute'])['EngagementIndex'].mean().sort_values()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_5656\1269285852.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  engagement_commute=df2.groupby(['commute'])['EngagementIndex'].mean().sort_values()

In [67]:
df2.groupby(['risk_rate'])['EngagementIndex'].agg(['mean','count'])

               mean  count
risk_rate
high       0.578976    153
low        0.576061    424
medium     0.572788    893

“Employees classified as high burnout risk still show relatively high engagement, suggesting that highly involved employees may be overexerting themselves.
    This indicates a potential risk of future burnout despite current engagement levels.”
Engagement levels remain relatively consistent across burnout risk groups, suggesting that employees at risk of burnout may still report moderate engagement. This indicates that engagement alone may not fully capture early burnout signals

In [13]:
engagement_overtime=pd.DataFrame(engagement_overtime)
engagement_overtime=engagement_overtime.reset_index()
engagement_overtime

  OverTime  EngagementIndex
0       No         0.566335
1      Yes         0.594752

In [20]:
a={'Max engagement in OverTime is':['Yes']}
a=pd.DataFrame(a)
a.reset_index(drop=True,inplace=True)
a
engagement_overtime=pd.concat([engagement_overtime,a],axis=(1))
engagement_overtime
# del engagement_overtime['Max engagement in OverTime is']

  OverTime  EngagementIndex Max engagement in OverTime is
0       No         0.566335                           Yes
1      Yes         0.594752                           NaN

In [16]:
engagement_travel=pd.DataFrame(engagement_travel)
engagement_travel=engagement_travel.reset_index()
engagement_travel

      BusinessTravel  EngagementIndex
0      Travel_Rarely         0.571508
1         Non-Travel         0.578333
2  Travel_Frequently         0.583032

In [22]:
b={'Max engagement in Travel Frequency is':['Travel_Frequently']}
b=pd.DataFrame(b)
b.reset_index(drop=True,inplace=True)
b
engagement_travel=pd.concat([engagement_travel,b],axis=(1))
engagement_travel
# del engagement_travel['Max engagement in Travel Frequency is']

      BusinessTravel  EngagementIndex Max engagement in Travel Frequency is
0      Travel_Rarely         0.571508                     Travel_Frequently
1         Non-Travel         0.578333                                   NaN
2  Travel_Frequently         0.583032                                   NaN

In [24]:
engagement_commute=pd.DataFrame(engagement_commute)
engagement_commute=engagement_commute.reset_index()
engagement_commute

    commute  EngagementIndex
0       far         0.572692
1      near         0.573840
2  very far         0.578014

In [25]:
c={'Max engagement in Commute is':['Very Far']}
c=pd.DataFrame(c)
c.reset_index(drop=True,inplace=True)
c
engagement_commute=pd.concat([engagement_commute,c],axis=(1))
engagement_commute

    commute  EngagementIndex Max engagement in Commute is
0       far         0.572692                     Very Far
1      near         0.573840                          NaN
2  very far         0.578014                          NaN

In [28]:
# engagement_index=pd.concat([engagement_overtime,engagement_travel,engagement_commute],axis=1)
engagement_index.rename(columns={'commute':'Commute'},inplace=True)
engagement_index
engagement_index.to_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\engagement index.csv')
# df.rename(columns={0:'risky_emp'},inplace=True)
# df

**Career-Stage Engagement Analysis**

In [110]:
df2['JobLevel'].unique()

array([2, 1, 3, 4, 5])

In [125]:
del df2['career_engagement']

In [240]:
bins=[1,3,4,5]
labels=['LOW(1-3)','MEDIUM(3-4)','HIGH(4-5)']
df2['career_engagement']=pd.cut(df2['JobLevel'],bins=bins,labels=labels,right=True,include_lowest=True)
df2['career_engagement']
# flagged_emp['risk_rate']=pd.cut(flagged_emp['WorkLifeBalance'],bins=bins,labels=labels,right=True,include_lowest=True)
# flagged_emp['risk_rate']

0       LOW(1-3)
1       LOW(1-3)
2       LOW(1-3)
3       LOW(1-3)
4       LOW(1-3)
          ...
1465    LOW(1-3)
1466    LOW(1-3)
1467    LOW(1-3)
1468    LOW(1-3)
1469    LOW(1-3)
Name: career_engagement, Length: 1470, dtype: category
Categories (3, object): ['LOW(1-3)' < 'MEDIUM(3-4)' < 'HIGH(4-5)']

In [140]:
del df2['career_engagement']

In [241]:
engagement_joblevel=df2.groupby(['career_engagement'])['EngagementIndex'].mean().sort_values()
engagement_joblevel=pd.DataFrame(engagement_joblevel)
engagement_joblevel=engagement_joblevel.reset_index()
engagement_joblevel=engagement_joblevel.rename(columns={'career_engagement':'JobLevel'})
engagement_joblevel
# df.rename(columns={0:'risky_emp'},inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12204\4185618666.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  engagement_joblevel=df2.groupby(['career_engagement'])['EngagementIndex'].mean().sort_values()

      JobLevel  EngagementIndex
0     LOW(1-3)         0.572329
1    HIGH(4-5)         0.582126
2  MEDIUM(3-4)         0.594340

In [253]:
a={'Max engagement in job level is':['MEDIUM(3-4)']}
a=pd.DataFrame(a)
a.reset_index(drop=True,inplace=True)
a
engagement_joblevel=pd.concat([engagement_joblevel,a],axis=(1))
engagement_joblevel

      JobLevel  EngagementIndex Max engagement in job level is
0     LOW(1-3)         0.572329                    MEDIUM(3-4)
1    HIGH(4-5)         0.582126                            NaN
2  MEDIUM(3-4)         0.594340                            NaN

In [204]:
engagement_years_at_company_=df2.groupby(['YearsAtCompany'])['EngagementIndex'].mean().sort_values()
engagement_years_at_company_.head()

YearsAtCompany
34    0.250000
29    0.458333
24    0.472222
27    0.500000
26    0.520833
Name: EngagementIndex, dtype: float64

In [242]:
bins=[1,5,20,40]
labels=['beginner(1-5)','intermediate(5-20)','professional(20-40)']
df2['year_at_company']=pd.cut(df2['YearsAtCompany'],bins=bins,labels=labels,right=True,include_lowest=True)
df2['year_at_company']

0       intermediate(5-20)
1       intermediate(5-20)
2                      NaN
3       intermediate(5-20)
4            beginner(1-5)
               ...
1465         beginner(1-5)
1466    intermediate(5-20)
1467    intermediate(5-20)
1468    intermediate(5-20)
1469         beginner(1-5)
Name: year_at_company, Length: 1470, dtype: category
Categories (3, object): ['beginner(1-5)' < 'intermediate(5-20)' < 'professional(20-40)']

In [243]:
engagement_years_at_company=df2.groupby(['year_at_company'])['EngagementIndex'].mean().sort_values()
engagement_years_at_company=pd.DataFrame(engagement_years_at_company)
engagement_years_at_company=engagement_years_at_company.reset_index()
engagement_years_at_company=engagement_years_at_company.rename(columns={'year_at_company':'Employee_Experience'})
engagement_years_at_company

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12204\1258144126.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  engagement_years_at_company=df2.groupby(['year_at_company'])['EngagementIndex'].mean().sort_values()

   Employee_Experience  EngagementIndex
0        beginner(1-5)         0.570241
1  professional(20-40)         0.570707
2   intermediate(5-20)         0.579352

In [258]:
b={'Max engagement in experience at company is':['intermediate(5-20)']}
b=pd.DataFrame(b)
b.reset_index(drop=True,inplace=True)
b
engagement_years_at_company=pd.concat([engagement_years_at_company,b],axis=(1))
engagement_years_at_company

,Employee_Experience,EngagementIndex,Max engagement in experience at company is
0,beginner(1-5),0.570241,intermediate(5-20)
1,professional(20-40),0.570707,NaN
2,intermediate(5-20),0.579352,NaN

In [214]:
df2['YearsInCurrentRole'].unique()

array([ 4,  7,  0,  2,  5,  9,  8,  3,  6, 13,  1, 15, 14, 16, 11, 10, 12,
       18, 17])

In [224]:
bins=[0,5,15,20]
labels=['New(0-5)','Mid-Tenure(5-15)', 'Experienced(15-20)']
df2['years_at_job']=pd.cut(df2['YearsInCurrentRole'],bins=bins,labels=labels,include_lowest=True)
df2['years_at_job'].head()

0            New(0-5)
1    Mid-Tenure(5-15)
2            New(0-5)
3    Mid-Tenure(5-15)
4            New(0-5)
Name: years_at_job, dtype: category
Categories (3, object): ['New(0-5)' < 'Mid-Tenure(5-15)' < 'Experienced(15-20)']

In [229]:
engagement_years_at_job= df2.groupby('years_at_job')['EngagementIndex'].mean().sort_values()
engagement_years_at_job=pd.DataFrame(engagement_years_at_job)
engagement_years_at_job=engagement_years_at_job.reset_index()
engagement_years_at_job
engagement_years_at_job=engagement_years_at_job.rename(columns={'years_at_job':'Years in current role'})
engagement_years_at_job

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12204\660727029.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  engagement_years_at_job= df2.groupby('years_at_job')['EngagementIndex'].mean().sort_values()

  Years in current role  EngagementIndex
0    Experienced(15-20)         0.480769
1              New(0-5)         0.573224
2      Mid-Tenure(5-15)         0.578913

In [259]:
c={'Max engagement in experience at current job in company is':['Mid-Tenure(5-15)']}
c=pd.DataFrame(c)
c.reset_index(drop=True,inplace=True)
c
engagement_years_at_job=pd.concat([engagement_years_at_job,c],axis=(1))
engagement_years_at_job

,Years in current role,EngagementIndex,Max engagement in experience at current job in company is
0,Experienced(15-20),0.480769,Mid-Tenure(5-15)
1,New(0-5),0.573224,NaN
2,Mid-Tenure(5-15),0.578913,NaN

In [261]:
CareerStageEngagement=pd.concat([engagement_joblevel,engagement_years_at_company,engagement_years_at_job],axis=1)
CareerStageEngagement
CareerStageEngagement.to_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\CareerStageEngagement.csv')

In [40]:
df2.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'risky_emp',
       'risk_rate', 'EngagementIndex', 'EngagementLevel'],
      dtype='object')

**Engagement vs Attrition**

In [7]:
df=pd.read_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\unified engagement level and risky emp .csv')
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,risky_emp,risk_rate,EngagementIndex,EngagementLevel
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,0.333333,Female,...,0,1,6,4,0,5,True,low,0.500000,Medium
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,0.666667,Male,...,3,3,10,7,1,7,False,medium,0.583333,Medium
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1.000000,Male,...,3,3,0,0,0,0,False,medium,0.583333,Medium
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1.000000,Female,...,3,3,8,7,3,0,False,medium,0.750000,High
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,0.000000,Male,...,3,3,2,2,2,2,False,medium,0.500000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,0.666667,Male,...,3,3,5,2,0,3,False,medium,0.833333,High
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,1.000000,Male,...,5,3,7,7,1,7,False,medium,0.333333,Low
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,0.333333,Male,...,0,3,6,2,0,3,False,medium,0.500000,Medium
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,1.000000,Male,...,3,2,9,6,0,8,False,low,0.666667,Medium
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,0.333333,Male,...,3,4,4,3,1,2,False,high,0.500000,Medium

In [34]:
engagement_attrition=df.groupby(['Attrition'])['EngagementIndex'].mean().sort_values()
engagement_attrition=pd.DataFrame(engagement_attrition)
engagement_attrition=engagement_attrition.reset_index()
engagement_attrition

   Attrition  EngagementIndex
0          1         0.504219
1          0         0.587862

In [43]:
d={'Max engagement is shown by':['Employees who left the company']}
d=pd.DataFrame(d)
d
engagement_attrition=pd.concat([engagement_attrition,d],axis=1)
engagement_attrition.to_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\engagement_attrition.csv')
engagement_attrition

   Attrition  EngagementIndex      Max engagement is shown by
0          1         0.504219  Employees who left the company
1          0         0.587862                             NaN

In [41]:
engagement_attrition

,Attrition,EngagementIndex,Max engagement is shown by,Max engagement is shown by,Max engagement is shown by
0,1,0.504219,Employees who left the company,Employees who left the company,Employees who left the company
1,0,0.587862,NaN,NaN,NaN

In [42]:
del engagement_attrition['Max engagement is shown by']

**power bi file**

In [27]:
del power_bi_csv

In [30]:
# df=df1.copy()
# power_bi_csv=df[(df['OverTime']=='Yes')&(df['WorkLifeBalance']<=2)]
# power_bi_csv=power_bi_csv.reset_index()
# power_bi_csv.index = power_bi_csv.index + 1
# del power_bi_csv['index']
# power_bi_csv
power_bi_csv.to_csv(r'C:\Users\LENOVO\Desktop\unified mentorship\burnout.csv',index=True)
# df[(df['OverTime'] == 'Yes') & (df['WorkLifeBalance'] <= 2)]

In [9]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [26]:
power_bi_csv

,index,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,...,3,1,0,8,0,1,6,4,0,5
1,6,59,0,Travel_Rarely,1324,Research & Development,3,3,Medical,3,...,4,1,3,12,3,2,1,0,0,0
2,16,32,0,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,...,3,4,2,7,5,2,6,2,0,5
3,17,22,0,Non-Travel,1123,Research & Development,16,2,Medical,4,...,3,2,2,1,2,2,1,0,0,0
4,34,24,1,Travel_Rarely,813,Research & Development,1,3,Medical,2,...,3,1,1,6,2,2,2,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,1374,58,0,Travel_Rarely,605,Sales,21,3,Life Sciences,4,...,3,3,1,29,2,2,1,0,0,0
122,1396,53,1,Travel_Rarely,1168,Sales,24,4,Life Sciences,1,...,3,2,0,15,2,2,2,2,2,2
123,1413,25,0,Travel_Rarely,977,Research & Development,2,1,Other,4,...,3,3,1,7,2,2,2,2,0,2
124,1419,42,0,Travel_Rarely,557,Research & Development,18,4,Life Sciences,4,...,3,3,1,9,3,2,4,3,1,2
125,1433,25,0,Travel_Rarely,1382,Sales,8,2,Other,1,...,4,2,1,6,3,2,5,3,0,4